use std::collections::HashSet;

pub fn get_python_stdlib_modules() -> HashSet<&'static str> {
    HashSet::from([
        // Core
        "abc",
        "argparse",
        "array",
        "ast",
        "asyncio",
        "base64",
        "binascii",
        "builtins",
        "collections",
        "concurrent",
        "contextlib",
        "copy",
        "datetime",
        "decimal",
        "enum",
        "functools",
        "gc",
        "glob",
        "hashlib",
        "heapq",
        "importlib",
        "inspect",
        "io",
        "itertools",
        "json",
        "logging",
        "math",
        "multiprocessing",
        "operator",
        "os",
        "pathlib",
        "pickle",
        "platform",
        "queue",
        "random",
        "re",
        "shutil",
        "signal",
        "socket",
        "sqlite3",
        "statistics",
        "string",
        "struct",
        "subprocess",
        "sys",
        "tempfile",
        "threading",
        "time",
        "timeit",
        "tkinter",
        "typing",
        "unittest",
        "urllib",
        "uuid",
        "warnings",
        "weakref",
        "xml",
        "zipfile",
        // Data Structures
        "array",
        "collections",
        "dataclasses",
        "enum",
        "heapq",
        "queue",
        // File and Directory Access
        "fileinput",
        "fnmatch",
        "linecache",
        "os.path",
        "pathlib",
        "stat",
        "tempfile",
        // Data Persistence
        "dbm",
        "pickle",
        "shelve",
        "sqlite3",
        // Data Compression
        "bz2",
        "gzip",
        "tarfile",
        "zipfile",
        // File Formats
        "configparser",
        "csv",
        "html",
        "json",
        "xml",
        // Cryptography
        "hashlib",
        "hmac",
        "secrets",
        // Internet Protocols
        "ftplib",
        "http",
        "imaplib",
        "poplib",
        "smtplib",
        "socketserver",
        "urllib",
        // Internet Data Handling
        "base64",
        "email",
        "json",
        "mimetypes",
        "urllib.parse",
        "uuid",
        // Development Tools
        "doctest",
        "pdb",
        "profile",
        "timeit",
        "trace",
        "unittest",
        // Runtime Features
        "atexit",
        "contextvars",
        "gc",
        "inspect",
        "site",
        "sys",
        "traceback",
        // Debug and Profiling
        "cProfile",
        "pdb",
        "timeit",
        "trace",
        // Software Packaging
        "distutils",
        "venv",
        // Math and Numbers
        "cmath",
        "decimal",
        "fractions",
        "math",
        "numbers",
        "random",
        "statistics",
        // Text Processing
        "difflib",
        "string",
        "textwrap",
        "unicodedata",
        // Structured Markup
        "html",
        "xml.etree.ElementTree",
        "xml.dom",
        "xml.sax",
        // Networking
        "asyncio",
        "socket",
        "ssl",
        "select",
        // GUI
        "tkinter",
        // System
        "platform",
        "sys",
        "os",
        // Concurrency
        "asyncio",
        "concurrent.futures",
        "multiprocessing",
        "threading",
        // Future
        "__future__",
        // Types
        "types",
    ])
}
